#!/bin/bash

# Note: this assumes that the system runs on Ubuntu. Currently tested on 11.10.

# Retrieve the prerequisites
sudo apt-get install git-core cmake freeglut3-dev pkg-config build-essential libxmu-dev libxi-dev libusb-1.0-0-dev

# Get the OpenKinect SDK
git clone git@github.com:OpenKinect/libfreenect.git

# Build OpenKinect
cd libfreenect
mkdir build
cd build
cmake ..
make

# Install OpenKinect
sudo make install
sudo ldconfig /usr/local/lib64/

# Install Prerequisites for OpenCV
sudo apt-get install libavformat-dev ffmpeg
sudo apt-get install libcv2.1 libcvaux2.1 libhighgui2.1 python-opencv opencv-doc libcv-dev libcvaux-dev libhighgui-dev
